#!/usr/bin/env python

import sys, os

SCRIPT_DIR = os.path.abspath('.')
SAMBA_DIR = os.path.abspath(sys.argv[0] + '/../../..')

LOCK_FILE = '.lock-wscript'
if not os.path.islink(LOCK_FILE):
    os.symlink(SAMBA_DIR + '/' + LOCK_FILE, LOCK_FILE)

os.chdir(SAMBA_DIR)
execfile("wscript")
Options.launch_dir = os.getcwd()
Options.SCRIPT_DIR = SCRIPT_DIR
Options.BUILD_DIR = Options.SCRIPT_DIR + '/build'

from TaskGen import feature, after
@feature('patch_bldpath')
@after('apply_link')
def patch_bldpath(self):
    t = self.link_task.outputs[0]
    try:
        os.makedirs(Options.BUILD_DIR)
    except:
        pass
    p = Options.BUILD_DIR + '/' + t.file()
    t.bldpath = lambda e=None: p
    t.abspath = lambda e=None: p
    t.nice_path = lambda e=None: p
