import os
from Configure import conf

top = '.'
out = 'build'
sambapath = os.path.abspath('../samba')

def options(ctx):
    ctx.load('compiler_c')
    ctx.add_option('--use-samba-tree-headers', dest='use_samba_tree_headers', action='store_true', default=False, help='Use header files in ../samba rather than public Samba header files (default=False)')

def configure(ctx):
    # Create header file to control how winexe gets built
    f = open(out + '/winexe_build.h', 'w')
    if ctx.options.use_samba_tree_headers:
        print('Using header files in Samba source tree')
        f.write('#define USE_SAMBA_TREE_HEADERS\n')
    else:
        print('Using public Samba header files')
        f.write('// Use public Samba header files\n')
    f.close()
    # Configure winexe
    ctx.find_program([ a + '-' + p + '-gcc' for a in ['i386', 'i586', 'i686' ] for p in ['mingw32', 'mingw32msvc', 'w64-mingw32'] ], var='CC_WIN32')
    ctx.find_program([ a + '-' + p + '-gcc' for a in ['x86_64', 'amd64'      ] for p in ['mingw32', 'mingw32msvc', 'w64-mingw32'] ], var='CC_WIN64')
    ctx.find_program('strip', var='STRIP')
    ctx.load('compiler_c')
    # Should also look for runtime files such as windows.h

    print "Patching Samba files"
    # Don't include pyldb-util because we can't statically link it
    os.system('cd ' + sambapath + ' && sed -i "s/ pyldb-util / /" lib/ldb-samba/wscript_build')
    # Patch Samba wscript_build to include this wscript in the Samba waf build tree
    os.system('cd ' + sambapath + ''' && grep -q "bld\.RECURSE('\.\./source') # added by winexe waf" wscript_build || sed -i "s^bld\.RECURSE('source3')^bld.RECURSE('source3')\\nbld.RECURSE('../source') # added by winexe waf^" wscript_build''')

    print "Chaining to Samba waf configure"
    os.system('cd ' + sambapath + ' && ./buildtools/bin/waf configure --bundled-libraries=ALL --nonshared-binary=winexe -C')

@conf
def windows_program(self, *k, **kw):
    '''Create task generator for compiling a Windows program
    Set keyword argument cc to the name of the compiler to use.
    '''
    kw['features'] = 'c cprogram'
    kw['env'] = self.env.copy()
    kw['env'].update({"CC": kw['cc'], "LINK_CC": kw['cc']})
    return self(*k, **kw)

def build(bld):
    if bld.env._SAMBA_BUILD_ == 4:
        # We have been called back by Samba waf.
        # Create a Samba-waf task generator for winexe
        bld.SAMBA_BINARY (
            binname='winexe',
            cflags='-ffunction-sections',
            ldflags='-Wl,--gc-sections',
            includes='#lib/popt',
            source='winexe.c svcinstall.c async.c build/winexesvc32_exe.c build/winexesvc64_exe.c',
            deps='POPT_SAMBA POPT_CREDENTIALS dcerpc')
        return
        # This fails if winexe has been compiled using public Samba headers.
        # In the latter case we need to link winexe with public libraries,
        # doing something somewhat equivalent to this:
        #     gcc -o winexe winexe_1.o svcinstall_1.o async_1.o build/winexesvc32_exe_1.o build/winexesvc64_exe_1.o -ltalloc -ltevent -ltdb -lldb -ldcerpc -lgensec -lregistry -lsamdb -lpopt -l:samba/liberrors.so -l:samba/libdcerpc-samba.so -l:samba/libcli-ldap.so -l:samba/ldb/ldbsamba_extensions.so

    # Create task generators for winexe components
    bld.windows_program(target='winexesvc32.exe', source='winexesvc_launch.c winexesvc_loop.c', cc=bld.env.CC_WIN32)
    bld.windows_program(target='winexesvc64.exe', source='winexesvc_launch.c winexesvc_loop.c', cc=bld.env.CC_WIN64)

    bld.program(target='bin2c', source='bin2c.c', cflags='')

    bld(rule='${SRC[0].abspath()} winexesvc32_exe ${SRC[1]} > ${TGT}', target='winexesvc32_exe.c', source='bin2c winexesvc32.exe')
    bld(rule='${SRC[0].abspath()} winexesvc64_exe ${SRC[1]} > ${TGT}', target='winexesvc64_exe.c', source='bin2c winexesvc64.exe')

    # Create a task generator for winexe (including hunks of Samba)
    bld(rule='cd ' + sambapath + ' && ./buildtools/bin/waf build --targets=winexe && cp -p bin/winexe ${TGT[0].abspath()} && ${STRIP} ${TGT[0].abspath()}',
        target='winexe',
        source='winexe.c svcinstall.c async.c winexesvc32_exe.c winexesvc64_exe.c')
